apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  owner: bravo
resources:
- configmap.yml
- serviceaccount.yml
- deployment.yml
- service.yml
- ingress.yml
- service-monitor.yml
- hpa.yml
images:
- name: giropops-senhas-python-chainguard
  newTag: local
